CREATE TABLE `content_import_jobs` (
  `id` VARCHAR(191) NOT NULL,
  `fileName` VARCHAR(500) NULL,
  `originalFileName` VARCHAR(500) NULL,
  `fileMimeType` VARCHAR(191) NULL,
  `fileSize` INTEGER NULL,
  `uploadedMediaId` VARCHAR(191) NULL,
  `sourceType` ENUM('WORD_DOCX', 'WORD_DOC', 'WEB_URL', 'WEB_SITEMAP', 'WEB_PAGE_BATCH', 'PDF_READY_FUTURE', 'HTML_READY_FUTURE', 'TEXT_READY_FUTURE') NOT NULL,
  `sourceUrl` VARCHAR(2048) NULL,
  `sourceDomain` VARCHAR(255) NULL,
  `sourceUrlsJson` JSON NULL,
  `sourceHash` VARCHAR(191) NULL,
  `status` ENUM('UPLOADED', 'VALIDATING', 'FETCHING', 'EXTRACTING', 'EXTRACTED', 'ANALYZING', 'ANALYZED', 'REVIEW_REQUIRED', 'APPROVED', 'IMPORTING', 'COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED', 'CANCELLED') NOT NULL DEFAULT 'UPLOADED',
  `extractionMode` ENUM('BASIC_EXTRACTION', 'AI_ASSISTED', 'RULE_BASED', 'HYBRID') NOT NULL DEFAULT 'BASIC_EXTRACTION',
  `importMode` ENUM('EXTRACT_AS_IS', 'SUMMARIZE_REWRITE', 'CLASSIFY_INTO_MODULES') NULL,
  `aiProvider` VARCHAR(100) NULL,
  `aiModel` VARCHAR(191) NULL,
  `extractedTextPreview` TEXT NULL,
  `extractedJson` JSON NULL,
  `analysisJson` JSON NULL,
  `mappingJson` JSON NULL,
  `warningsJson` JSON NULL,
  `robotsPolicyJson` JSON NULL,
  `scrapeSettingsJson` JSON NULL,
  `attributionJson` JSON NULL,
  `errorMessage` TEXT NULL,
  `createdById` VARCHAR(191) NULL,
  `reviewedById` VARCHAR(191) NULL,
  `completedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,

  PRIMARY KEY (`id`),
  INDEX `content_import_jobs_status_idx` (`status`),
  INDEX `content_import_jobs_sourceType_idx` (`sourceType`),
  INDEX `content_import_jobs_sourceDomain_idx` (`sourceDomain`),
  INDEX `content_import_jobs_sourceUrl_idx` (`sourceUrl`(191)),
  INDEX `content_import_jobs_sourceHash_idx` (`sourceHash`),
  INDEX `content_import_jobs_createdById_idx` (`createdById`),
  INDEX `content_import_jobs_createdAt_idx` (`createdAt`),
  INDEX `content_import_jobs_deletedAt_idx` (`deletedAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `content_import_items` (
  `id` VARCHAR(191) NOT NULL,
  `importJobId` VARCHAR(191) NOT NULL,
  `sourceSectionId` VARCHAR(191) NULL,
  `sourceUrl` VARCHAR(2048) NULL,
  `sourceTitle` VARCHAR(500) NULL,
  `sourceCanonicalUrl` VARCHAR(2048) NULL,
  `sourcePublishedAt` DATETIME(3) NULL,
  `sourceAuthor` VARCHAR(255) NULL,
  `sourceHash` VARCHAR(191) NULL,
  `importedFromWeb` BOOLEAN NOT NULL DEFAULT false,
  `detectedContentType` ENUM('PAGE', 'BLOG', 'FAQ', 'ANNOUNCEMENT', 'NOTICE', 'CIRCULAR', 'OFFICE_ORDER', 'TENDER', 'SCHEME', 'SERVICE', 'NEWSROOM', 'PRESS_RELEASE', 'RTI_DISCLOSURE', 'DEPARTMENT_PAGE', 'DOCUMENT', 'MEDIA_GALLERY', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  `targetModuleKey` VARCHAR(100) NULL,
  `targetEntityType` VARCHAR(100) NULL,
  `targetEntityId` VARCHAR(191) NULL,
  `title` VARCHAR(500) NOT NULL,
  `slug` VARCHAR(191) NULL,
  `summary` TEXT NULL,
  `bodyJson` JSON NULL,
  `extractedImagesJson` JSON NULL,
  `extractedTablesJson` JSON NULL,
  `extractedLinksJson` JSON NULL,
  `sourceAttributionJson` JSON NULL,
  `fieldMappingJson` JSON NULL,
  `metadataJson` JSON NULL,
  `confidenceScore` DOUBLE NULL,
  `status` ENUM('DRAFT_MAPPING', 'REVIEW_REQUIRED', 'APPROVED_FOR_IMPORT', 'IMPORTED', 'SKIPPED', 'FAILED') NOT NULL DEFAULT 'DRAFT_MAPPING',
  `reviewNotes` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,

  PRIMARY KEY (`id`),
  INDEX `content_import_items_importJobId_idx` (`importJobId`),
  INDEX `content_import_items_sourceUrl_idx` (`sourceUrl`(191)),
  INDEX `content_import_items_sourceHash_idx` (`sourceHash`),
  INDEX `content_import_items_detectedContentType_idx` (`detectedContentType`),
  INDEX `content_import_items_targetModuleKey_idx` (`targetModuleKey`),
  INDEX `content_import_items_status_idx` (`status`),
  INDEX `content_import_items_deletedAt_idx` (`deletedAt`),
  CONSTRAINT `content_import_items_importJobId_fkey` FOREIGN KEY (`importJobId`) REFERENCES `content_import_jobs` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `content_import_assets` (
  `id` VARCHAR(191) NOT NULL,
  `importJobId` VARCHAR(191) NOT NULL,
  `importItemId` VARCHAR(191) NULL,
  `originalFileName` VARCHAR(500) NULL,
  `assetType` ENUM('IMAGE', 'TABLE', 'DOCUMENT', 'LINK', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  `mediaId` VARCHAR(191) NULL,
  `extractedPath` VARCHAR(2048) NULL,
  `sourceUrl` VARCHAR(2048) NULL,
  `sourceAltText` VARCHAR(500) NULL,
  `sourceCaption` TEXT NULL,
  `sourceLicenseInfo` TEXT NULL,
  `altText` VARCHAR(500) NULL,
  `caption` TEXT NULL,
  `status` ENUM('EXTRACTED', 'SAVED_TO_MEDIA', 'LINKED_TO_CONTENT', 'SKIPPED', 'FAILED') NOT NULL DEFAULT 'EXTRACTED',
  `metadataJson` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  INDEX `content_import_assets_importJobId_idx` (`importJobId`),
  INDEX `content_import_assets_importItemId_idx` (`importItemId`),
  INDEX `content_import_assets_assetType_idx` (`assetType`),
  INDEX `content_import_assets_status_idx` (`status`),
  CONSTRAINT `content_import_assets_importJobId_fkey` FOREIGN KEY (`importJobId`) REFERENCES `content_import_jobs` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `content_import_assets_importItemId_fkey` FOREIGN KEY (`importItemId`) REFERENCES `content_import_items` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `content_import_rules` (
  `id` VARCHAR(191) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `isEnabled` BOOLEAN NOT NULL DEFAULT true,
  `priority` INTEGER NOT NULL DEFAULT 100,
  `matchType` ENUM('HEADING_CONTAINS', 'TEXT_CONTAINS', 'REGEX', 'DOCUMENT_TITLE', 'SECTION_PATTERN', 'URL_CONTAINS', 'DOMAIN_EQUALS', 'PATH_CONTAINS', 'META_TYPE', 'OPEN_GRAPH_TYPE', 'AI_CLASSIFICATION') NOT NULL,
  `matchPattern` VARCHAR(1000) NOT NULL,
  `targetModuleKey` VARCHAR(100) NOT NULL,
  `targetEntityType` VARCHAR(100) NOT NULL,
  `mappingConfigJson` JSON NULL,
  `createdById` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,

  PRIMARY KEY (`id`),
  INDEX `content_import_rules_isEnabled_idx` (`isEnabled`),
  INDEX `content_import_rules_targetModuleKey_idx` (`targetModuleKey`),
  INDEX `content_import_rules_priority_idx` (`priority`),
  INDEX `content_import_rules_deletedAt_idx` (`deletedAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `content_import_logs` (
  `id` VARCHAR(191) NOT NULL,
  `importJobId` VARCHAR(191) NOT NULL,
  `importItemId` VARCHAR(191) NULL,
  `action` VARCHAR(191) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `message` TEXT NULL,
  `metadataJson` JSON NULL,
  `createdById` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`),
  INDEX `content_import_logs_importJobId_idx` (`importJobId`),
  INDEX `content_import_logs_importItemId_idx` (`importItemId`),
  INDEX `content_import_logs_createdAt_idx` (`createdAt`),
  CONSTRAINT `content_import_logs_importJobId_fkey` FOREIGN KEY (`importJobId`) REFERENCES `content_import_jobs` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `content_import_logs_importItemId_fkey` FOREIGN KEY (`importItemId`) REFERENCES `content_import_items` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO `cms_modules` (
  `id`,
  `moduleKey`,
  `moduleName`,
  `description`,
  `category`,
  `version`,
  `icon`,
  `routePath`,
  `publicRoutePath`,
  `isSystemModule`,
  `isCoreModule`,
  `isEnabledGlobally`,
  `isPublicEnabled`,
  `isAdminVisible`,
  `isTemplateAvailable`,
  `dependsOnJson`,
  `permissionsJson`,
  `settingsJson`,
  `createdAt`,
  `updatedAt`
) VALUES (
  CONCAT('content_importer_', REPLACE(UUID(), '-', '')),
  'content_importer',
  'AI Content Importer',
  'Word and public web-to-CMS draft generation with review-before-import workflow.',
  'AI',
  '1.0.0',
  'Sparkles',
  '/ai/content-importer',
  NULL,
  false,
  false,
  true,
  false,
  true,
  false,
  JSON_ARRAY('ai_providers', 'media'),
  JSON_ARRAY(
    'content_importer.view',
    'content_importer.upload',
    'content_importer.word_import',
    'content_importer.web_import',
    'content_importer.web_validate',
    'content_importer.web_batch_import',
    'content_importer.web_sitemap_import',
    'content_importer.web_image_import',
    'content_importer.extract',
    'content_importer.ai_analyze',
    'content_importer.review',
    'content_importer.approve_item',
    'content_importer.import_item',
    'content_importer.import_bulk',
    'content_importer.cancel_job',
    'content_importer.delete_job',
    'content_importer.rules.view',
    'content_importer.rules.create',
    'content_importer.rules.update',
    'content_importer.rules.delete',
    'content_importer.logs.view'
  ),
  JSON_OBJECT(
    'maxBatchUrls', 10,
    'maxSitemapUrls', 25,
    'respectRobotsDefault', true,
    'draftOnly', true
  ),
  CURRENT_TIMESTAMP(3),
  CURRENT_TIMESTAMP(3)
) ON DUPLICATE KEY UPDATE
  `moduleName` = VALUES(`moduleName`),
  `description` = VALUES(`description`),
  `category` = VALUES(`category`),
  `icon` = VALUES(`icon`),
  `routePath` = VALUES(`routePath`),
  `publicRoutePath` = VALUES(`publicRoutePath`),
  `isPublicEnabled` = VALUES(`isPublicEnabled`),
  `isAdminVisible` = VALUES(`isAdminVisible`),
  `isTemplateAvailable` = VALUES(`isTemplateAvailable`),
  `dependsOnJson` = VALUES(`dependsOnJson`),
  `permissionsJson` = VALUES(`permissionsJson`),
  `settingsJson` = VALUES(`settingsJson`),
  `updatedAt` = CURRENT_TIMESTAMP(3);
