'use client';

import { useEffect, useState } from 'react';
import { Check, Code, Loader2, Play, Save, X } from 'lucide-react';
import { AdminPageShell } from '@/components/layout/admin-page-shell';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { apiClient } from '@/lib/api-client';
import type { AuthUser } from '@/types/auth';

interface SchemaSettings {
  enableGlobalSchema: boolean;
  enablePageSchema: boolean;
  enableBlogSchema: boolean;
  enableFaqSchema: boolean;
  enableBreadcrumbSchema: boolean;
  enableDocumentSchema: boolean;
  enableSearchActionSchema: boolean;
  defaultPublisherName: string | null;
  defaultPublisherLogo: string | null;
}

interface SchemaEntry {
  id: string;
  sourceType: string;
  sourceId: string | null;
  schemaType: string;
  status: string;
  isAutoGenerated: boolean;
  generatedByAi: boolean;
  updatedAt: string;
}

function SchemaContent({ user }: { user: AuthUser }) {
  const [settings, setSettings] = useState<SchemaSettings | null>(null);
  const [entries, setEntries] = useState<SchemaEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [success, setSuccess] = useState<string | null>(null);

  useEffect(() => { loadData(); }, []);

  async function loadData() {
    try {
      const [s, e] = await Promise.all([
        apiClient<SchemaSettings>('/api/structured-data/settings'),
        apiClient<SchemaEntry[]>('/api/structured-data/entries'),
      ]);
      setSettings(s);
      setEntries(e);
    } catch {}
    setLoading(false);
  }

  async function handleSave() {
    if (!settings) return;
    setSaving(true); setSuccess(null);
    try { await apiClient('/api/structured-data/settings', { method: 'PUT', body: JSON.stringify(settings) }); setSuccess('Settings saved.'); } catch {}
    setSaving(false);
  }

  function updateSetting<K extends keyof SchemaSettings>(key: K, value: SchemaSettings[K]) {
    setSettings(prev => prev ? { ...prev, [key]: value } : null);
  }

  if (loading) return <div className="flex justify-center py-12"><Loader2 className="h-6 w-6 animate-spin" /></div>;

  const statusColors: Record<string, string> = { ACTIVE: 'bg-emerald-100 text-emerald-700', DRAFT: 'bg-blue-100 text-blue-700', DISABLED: 'bg-gray-100 text-gray-700', INVALID: 'bg-red-100 text-red-700' };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold">Schema / Structured Data</h1>
          <p className="mt-1 text-sm text-muted-foreground">Manage JSON-LD structured data for SEO and rich search results.</p>
        </div>
        <Button onClick={handleSave} disabled={saving}>{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />} Save Settings</Button>
      </div>

      {success && <div className="rounded-md border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-700">{success}</div>}

      {/* Schema Toggles */}
      <Card>
        <CardHeader><CardTitle className="text-base">Schema Types</CardTitle><CardDescription>Enable or disable automatic schema generation per content type.</CardDescription></CardHeader>
        <CardContent className="space-y-4">
          {[
            { key: 'enableGlobalSchema' as const, label: 'Global Website & Organization', desc: 'WebSite + Organization schema on all pages' },
            { key: 'enablePageSchema' as const, label: 'Page Schema', desc: 'WebPage schema for published pages' },
            { key: 'enableBlogSchema' as const, label: 'Blog Schema', desc: 'BlogPosting schema for published blog posts' },
            { key: 'enableFaqSchema' as const, label: 'FAQ Schema', desc: 'FAQPage schema for published FAQs' },
            { key: 'enableBreadcrumbSchema' as const, label: 'Breadcrumb Schema', desc: 'BreadcrumbList for navigation context' },
            { key: 'enableDocumentSchema' as const, label: 'Document Schema', desc: 'DigitalDocument schema for published documents' },
            { key: 'enableSearchActionSchema' as const, label: 'Search Action', desc: 'SearchAction in WebSite schema for sitelinks search' },
          ].map(item => (
            <div key={item.key} className="flex items-center justify-between">
              <div><p className="text-sm font-medium">{item.label}</p><p className="text-xs text-muted-foreground">{item.desc}</p></div>
              <Switch checked={settings?.[item.key] ?? false} onCheckedChange={(v) => updateSetting(item.key, v)} />
            </div>
          ))}
        </CardContent>
      </Card>

      {/* Publisher Info */}
      <Card>
        <CardHeader><CardTitle className="text-base">Publisher / Organization</CardTitle><CardDescription>Used in BlogPosting and Organization schema.</CardDescription></CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Publisher Name</Label>
              <Input value={settings?.defaultPublisherName || ''} onChange={(e) => updateSetting('defaultPublisherName', e.target.value)} placeholder="Organization name" />
            </div>
            <div className="space-y-2">
              <Label>Publisher Logo URL</Label>
              <Input value={settings?.defaultPublisherLogo || ''} onChange={(e) => updateSetting('defaultPublisherLogo', e.target.value)} placeholder="https://example.com/logo.png" />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Entries */}
      <Card>
        <CardHeader><CardTitle className="text-base">Schema Entries ({entries.length})</CardTitle><CardDescription>Manually created or auto-generated structured data entries.</CardDescription></CardHeader>
        <CardContent>
          {entries.length === 0 ? (
            <p className="text-center py-8 text-muted-foreground">No schema entries yet. They are auto-generated when content is published.</p>
          ) : (
            <div className="space-y-2">
              {entries.map(entry => (
                <div key={entry.id} className="flex items-center gap-3 rounded-md border p-3">
                  <Code className="h-4 w-4 text-muted-foreground shrink-0" />
                  <div className="flex-1">
                    <p className="text-sm font-medium">{entry.schemaType.replace('_', ' ')}</p>
                    <p className="text-xs text-muted-foreground">{entry.sourceType} {entry.sourceId ? `• ${entry.sourceId.substring(0, 8)}...` : '• Global'}</p>
                  </div>
                  <span className={`text-xs px-2 py-0.5 rounded-full ${statusColors[entry.status] || ''}`}>{entry.status}</span>
                  {entry.isAutoGenerated && <span className="text-xs text-muted-foreground">Auto</span>}
                  {entry.generatedByAi && <span className="text-xs text-purple-600">AI</span>}
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

export default function SchemaPage() {
  return <AdminPageShell sectionTitle="Structured Data">{(user) => <SchemaContent user={user} />}</AdminPageShell>;
}
