/**
 * All available permissions grouped by module.
 */
export const PERMISSION_GROUPS = {
  dashboard: {
    label: 'Dashboard',
    permissions: ['dashboard.view'],
  },
  users: {
    label: 'Users',
    permissions: [
      'users.view',
      'users.create',
      'users.update',
      'users.delete',
      'users.change_status',
    ],
  },
  roles: {
    label: 'Roles',
    permissions: [
      'roles.view',
      'roles.create',
      'roles.update',
      'roles.delete',
      'roles.update_permissions',
    ],
  },
  pages: {
    label: 'Pages',
    permissions: [
      'pages.view',
      'pages.create',
      'pages.update',
      'pages.delete',
      'pages.submit',
      'pages.approve',
      'pages.publish',
    ],
  },
  blogs: {
    label: 'Blogs',
    permissions: [
      'blogs.view',
      'blogs.create',
      'blogs.update',
      'blogs.delete',
      'blogs.submit',
      'blogs.approve',
      'blogs.publish',
    ],
  },
  media: {
    label: 'Media',
    permissions: ['media.view', 'media.upload', 'media.update', 'media.delete'],
  },
  workflow: {
    label: 'Workflow',
    permissions: [
      'workflow.view',
      'workflow.request_changes',
      'workflow.approve',
      'workflow.publish',
    ],
  },
  ai: {
    label: 'AI',
    permissions: ['ai.use', 'ai.view_usage'],
  },
  content_importer: {
    label: 'AI Content Importer',
    permissions: [
      'content_importer.view',
      'content_importer.upload',
      'content_importer.word_import',
      'content_importer.web_import',
      'content_importer.web_validate',
      'content_importer.web_batch_import',
      'content_importer.web_sitemap_import',
      'content_importer.web_image_import',
      'content_importer.extract',
      'content_importer.ai_analyze',
      'content_importer.review',
      'content_importer.approve_item',
      'content_importer.import_item',
      'content_importer.import_bulk',
      'content_importer.cancel_job',
      'content_importer.delete_job',
      'content_importer.rules.view',
      'content_importer.rules.create',
      'content_importer.rules.update',
      'content_importer.rules.delete',
      'content_importer.logs.view',
    ],
  },
  chatbot: {
    label: 'Chatbot',
    permissions: [
      'chatbot.view',
      'chatbot.settings',
      'chatbot.view_conversations',
      'chatbot.view_leads',
    ],
  },
  settings: {
    label: 'Settings',
    permissions: ['settings.view', 'settings.update'],
  },
  notifications: {
    label: 'Notifications',
    permissions: ['notifications.view', 'notifications.update'],
  },
  audit_logs: {
    label: 'Audit Logs',
    permissions: ['audit_logs.view'],
  },
  email_logs: {
    label: 'Email Logs',
    permissions: ['email_logs.view'],
  },
} as const;

/** Flat list of all valid permission keys */
export const ALL_PERMISSIONS: string[] = Object.values(PERMISSION_GROUPS).flatMap(
  (group) => [...group.permissions],
);

/** Default permissions for each system role */
export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  'Super Admin': [...ALL_PERMISSIONS],
  Admin: [
    'dashboard.view',
    'users.view',
    'users.create',
    'users.update',
    'users.delete',
    'users.change_status',
    'roles.view',
    'pages.view',
    'pages.create',
    'pages.update',
    'pages.delete',
    'pages.submit',
    'pages.approve',
    'pages.publish',
    'blogs.view',
    'blogs.create',
    'blogs.update',
    'blogs.delete',
    'blogs.submit',
    'blogs.approve',
    'blogs.publish',
    'media.view',
    'media.upload',
    'media.update',
    'media.delete',
    'workflow.view',
    'workflow.request_changes',
    'workflow.approve',
    'workflow.publish',
    'ai.use',
    'ai.view_usage',
    ...PERMISSION_GROUPS.content_importer.permissions,
    'chatbot.view',
    'chatbot.settings',
    'chatbot.view_conversations',
    'chatbot.view_leads',
    'settings.view',
    'settings.update',
    'notifications.view',
    'notifications.update',
    'audit_logs.view',
    'email_logs.view',
  ],
  Editor: [
    'dashboard.view',
    'pages.view',
    'pages.create',
    'pages.update',
    'pages.submit',
    'blogs.view',
    'blogs.create',
    'blogs.update',
    'blogs.submit',
    'media.view',
    'media.upload',
    'media.update',
    'workflow.view',
    'ai.use',
    'ai.view_usage',
    'content_importer.view',
    'content_importer.upload',
    'content_importer.word_import',
    'content_importer.web_import',
    'content_importer.web_validate',
    'content_importer.extract',
    'content_importer.ai_analyze',
    'content_importer.review',
    'content_importer.rules.view',
    'content_importer.logs.view',
    'notifications.view',
    'notifications.update',
  ],
  Reviewer: [
    'dashboard.view',
    'pages.view',
    'blogs.view',
    'media.view',
    'workflow.view',
    'workflow.request_changes',
    'workflow.approve',
    'ai.use',
    'ai.view_usage',
    'content_importer.view',
    'content_importer.review',
    'content_importer.rules.view',
    'content_importer.logs.view',
    'notifications.view',
    'notifications.update',
  ],
  Publisher: [
    'dashboard.view',
    'pages.view',
    'pages.publish',
    'blogs.view',
    'blogs.publish',
    'media.view',
    'workflow.view',
    'workflow.publish',
    'content_importer.view',
    'content_importer.review',
    'content_importer.approve_item',
    'content_importer.import_item',
    'content_importer.import_bulk',
    'content_importer.web_image_import',
    'content_importer.logs.view',
    'notifications.view',
    'notifications.update',
  ],
  Viewer: [
    'dashboard.view',
    'pages.view',
    'blogs.view',
    'media.view',
    'notifications.view',
  ],
};
